version: '2'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: luna_password
      MONGO_INITDB_DATABASE: luna
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data/:/data
    command: server /data --console-address ":9001"
